version: 0.2
# Setting up environment variables
env:
  variables:
    AWS_ACCOUNT_ID: "017602359561"
    ECR_REPOSITORY_NAME: "python-rest-api"
    AWS_REGION: "ap-south-1"
    REPOSITORY_URI: "017602359561.dkr.ecr.ap-south-1.amazonaws.com/python-rest-api"
phases:
  pre_build:
  # Logging into ECR
    commands:
      - echo "Logging in to ECR"
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
      # Tagging the Image with latest-"last commit id"
      - export COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export IMAGE_TAG=latest-$COMMIT_HASH
  build:
    commands:
      # Build Docker Image And Push To ECR Repository
      - docker build --no-cache -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:$IMAGE_TAG -f Dockerfile .
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`